---
- name: Configure 802.1X on NX-OS devices with a template
  hosts: devnet-nxos
  gather_facts: no
  vars:
    ansible_become: yes
    ansible_become_method: enable
  roles:
    - ansible-network.network-engine
  tasks:
    - name: Get CDP neighbors
      ansible.utils.cli_parse:
        command: show cdp neighbors
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: show_cdp_output
    - name: Set interface description based on LLDP
      cisco.nxos.nxos_config:
        lines:
          - '{{ lookup("template", "templates/interface.j2") }}'
      loop: '{{ show_cdp_output }}'
