---
- name: Get ARP information
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: show ip arp
      raw: "show ip arp"

      register: show_ip_arp

    - debug: var=show_ip_arp.stdout_lines
