---
- name: Configure 802.1X on NX-OS devices with a template
  hosts: devnet_nxos
  gather_facts: no
  vars:
    ansible_become: yes
    ansible_become_method: enable
  tasks:
  - name: Gather device facts
    cisco.nxos.nxos_facts:
      gather_subset: all
    register: facts
  # - debug:
  #     msg: '{{ facts | port_description }}'
  - name: Set interface description based on LLDP
    cisco.nxos.nxos_interfaces:
      config:
        - name: '{{ item.name }}'
          description: "{{ item.name }} is connected to {{ item.connected_device }}"
    loop: '{{ facts | port_description }}'
