---
- name: Configure 802.1X on NX-OS devices
  hosts: devnet_nxos
  gather_facts: no
  vars:
    ansible_become: yes
    ansible_become_method: enable
  roles:
    - ansible-network.network-engine
  tasks:
    - name: Get CDP neighbors
      ansible.utils.cli_parse:
        command: show cdp neighbors
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: show_cdp_output
    - debug:
        var: show_cdp_output
    - name: Set interface description based on CDP
      cisco.nxos.nxos_interfaces:
        config:
          - name: '{{ item.local_interface }}'
            description: "{{ item.local_interface }} is connected to {{ item.neighbor }}"
      loop: '{{ show_cdp_output }}'
