- name: "Write subset of facts to output files using jinja2 templates"
  hosts: devnet
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
    - name: Gather facts (nxos)
      cisco.nxos.nxos_facts:
      when: ansible_network_os == 'cisco.nxos.nxos'

    - name: Gather facts (ios)
      cisco.ios.ios_facts:
      when: ansible_network_os == 'cisco.ios.ios'

    ###
    # Demonstrate variables
    #
    - name: Display OS version by hostname from facts
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
      tags: facts

    - name: Facts from a specific host
      debug:
        var: hostvars['DIST-RTR01']
      run_once: yes
      tags: facts

    - name: Create facts dir to store facts output
      file:
        path: "./facts/"
        state: directory
        recurse: yes
      run_once: yes
      tags: facts

    - name: Write facts to disk using an inline template
      copy:
        content: |
          #jinja2: lstrip_blocks: True
          NXOS device info:
            {% for host in groups['devnet_nxos'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}

          IOS device info:
            {% for host in groups['devnet_ios'] %}
            Hostname: {{ hostvars[host].ansible_net_hostname }}
            Version: {{ hostvars[host].ansible_net_version }}
            Model: {{ hostvars[host].ansible_net_model }}
            Serial: {{ hostvars[host].ansible_net_serialnum }}
            {% endfor %}
        dest: ./facts/switch-facts.txt
      run_once: yes
      tags: facts

    - name: Write facts to disk using a template file
      template:
        src: templates/facts_output.j2
        dest: ./facts/switch-facts_from_template_file.txt
      run_once: yes
      tags: facts

    ###
    # Get running configuration and save to file
    #

    - name: Backup NXOS devices
      cisco.nxos.nxos_config:
        backup: yes
      register: backup_nxos_location
      when: ansible_network_os == 'cisco.nxos.nxos'
      tags: backup

    - name: Backup IOS devices
      cisco.ios.ios_config:
        backup: yes
      register: backup_ios_location
      when: ansible_network_os == 'cisco.ios.ios'
      tags: backup

    - name: Create backup dir to store backup files
      file:
        path: "./backups/"
        state: directory
        recurse: yes
      run_once: yes
      tags: backup

    - name: Copy backup files into /tmp/backups/ (nxos)
      copy:
        src: "{{ backup_nxos_location.backup_path }}"
        dest: "./backups/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.nxos.nxos'
      tags: backup

    - name: Copy backup files into /tmp/backups/ (ios)
      copy:
        src: "{{ backup_ios_location.backup_path }}"
        dest: "./backups/{{ inventory_hostname }}.txt"
      when: ansible_network_os == 'cisco.ios.ios'
      tags: backup