---
- name: Set global configurations
  hosts: devnet_ios
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_become: yes
    ansible_become_method: enable
    recommended_version: "18.03.01"
  tasks:
  - set_fact:
      ntp_servers_data_structure: []
  - set_fact:
      ntp_servers_data_structure: "{{ [{'server': item}] + ntp_servers_data_structure }}"
    loop: '{{ ntp_servers }}'
  - name: Set NTP servers
    cisco.ios.ios_ntp_global:
      config:
        servers: '{{ ntp_servers_data_structure }}'
  - name: Set DNS servers
    cisco.ios.ios_config:
      lines: 'ip name-server {{ dns_servers[0] }}'
