---
- name: Query IOS-XE version
  hosts: devnet-ios
  gather_facts: false
  vars:
    ansible_become: yes
    ansible_become_method: enable
    recommended_version: "18.03.01"
  tasks:
  - set_fact:
      routers_to_upgrade: []
  - name: Gather device facts
    cisco.ios.ios_facts:
      gather_subset: all
    register: facts
  - set_fact:
      router: '{{ facts.ansible_facts.ansible_net_hostname }}'
  - set_fact:
      routers_to_upgrade: '{{ routers_to_upgrade + [router] }}'
    when: facts.ansible_facts.ansible_net_version is version(recommended_version, '<')
  - debug:
      msg: "The following devices should be upgraded: {{ routers_to_upgrade }}"
