---
- name: Run commands that require answering a prompt
  hosts: devnet_ios
  gather_facts: false


  tasks:
    - name: Clear counters Gi1 & Gi2 - IOS
      cisco.ios.ios_command:
        commands:
          - command: 'clear counters GigabitEthernet1'
            prompt: 'Clear "show interface" counters on this interface \[confirm\]'
            answer: 'y'
          - command: 'clear counters GigabitEthernet2'
            prompt: '[confirm]'
            answer: "\r"
      when: ansible_network_os=='cisco.ios.ios'


